name: CI/CD Test1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "Jugal@1998" | docker login -u "jpraneth07@gmail.com" --password-stdin
      - name: Build, tag, and push image to DockerHub
        env:
          DOCKERHUB_USERNAME: jugal11
          IMAGE_NAME: my-image
        run: |
          docker build -t jugal11/$IMAGE_NAME .
          docker push jugal11/$IMAGE_NAME:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest test.py
